version: '3.8'

services:
  app:
    build: .
    ports:
      - "1488:1488"
    depends_on:
      - db
    links:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=567kybik
      - DB_DATABASE=ecom

  db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=567kybik
      - MYSQL_DATABASE=ecom
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata: