version: '3'
services:
  db:
    image: mysql:latest
    container_name: sqldb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=567kybik
      - MYSQL_DATABASE=ecom
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    volumes:
      - mysqldata:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mybackend
    ports:
      - "1488:1488"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_NAME=ecom

volumes:
  mysqldata:
